
import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{onAuthStateChanged,User}from"firebase/auth";
import{doc,getDoc,setDoc}from"firebase/firestore";
import{BarChart3,CalendarCheck,ChevronRight,ClipboardCheck,Coins,Database,Download,FileText,Gift,Home,LogIn,LogOut,Package,Plus,RotateCcw,Save,Settings,Star,Trash2,Trophy,Users}from"lucide-react";
import{auth,db,firebaseReady,loginWithGoogle,logout}from"./firebase";
import"./style.css";

type Character={id:string;name:string;memo:string;order:number;world?:string;job?:string;level?:string};
type Boss={id:string;order:number;name:string;difficulty:string;cycle:string;price:number};
type Run={id:string;characterId:string;bossId:string;cleared:boolean;vipReset:boolean;partySize:number;memo:string};
type Task={id:string;characterId:string;title:string;type:"daily"|"weekly"|"event";done:boolean};
type Drop={id:string;characterId:string;bossId:string;itemId:string;itemName:string;category:string;quantity:number;obtainedAt:number;memo:string};
type Fragment={id:string;characterId:string;name:string;part:string;current:number;required:number;weekly:number};
type Growth={id:string;characterId:string;date:number;score:string;mainStat:string;patch:string;memo:string};
type Settlement={id:string;createdAt:number;totalIncome:number;totalCrystals:number;names:string[]};
type AppState={characters:Character[];bosses:Boss[];runs:Run[];tasks:Task[];drops:Drop[];fragments:Fragment[];growths:Growth[];settlements:Settlement[];selectedCharacterId:string;vipRank:string;customVipSlots:number;compact:boolean};

const LOCAL_KEY="maple-manager-trace-final-v1";const BASE_SELL_LIMIT=12;
const bossSeed:[string,string,string,number][]= [
["シグナス","Easy","週",7380000],["ヒルラ","Hard","週",9010000],["ピンクビーン","Chaos","週",9450000],["シグナス","Normal","週",10530000],
["ジャクム","Chaos","週",11150000],["ピエール","Chaos","週",11150000],["バンバン","Chaos","週",11150000],["ブラッディクイーン","Chaos","週",11150000],
["マグナス","Hard","週",12170000],["ベルルム","Chaos","週",13450000],["ノウ姫","Normal","週",14430000],["ビシャス","Chaos","週",16500000],
["アケチミツヒデ","Normal","週",17970000],["スウ","Normal","週",20790000],["デミアン","Normal","週",22170000],["ガーディアンエンジェルスライム","Normal","週",30890000],
["ルシード","Easy","週",37570000],["ウィル","Easy","週",41050000],["ルシード","Normal","週",43660000],["ウィル","Normal","週",49720000],
["ダスク","Normal","週",53090000],["デュンケル","Normal","週",56560000],["デミアン","Hard","週",61690000],["スウ","Hard","週",63620000],
["ルシード","Hard","週",70310000],["ダスク","Chaos","週",81360000],["真ヒルラ","Normal","週",82790000],["ガーディアンエンジェルスライム","Chaos","週",85530000],
["ウィル","Hard","週",86220000],["デュンケル","Hard","週",90870000],["真ヒルラ","Hard","週",102500000],["最初の対敵者","Easy","週",146400000],
["セレン","Normal","週",175000000],["カロス","Easy","週",178500000],["セレン","Hard","週",186040000],["最初の対敵者","Normal","週",221300000],
["カリーン","Easy","週",225970000],["カロス","Normal","週",254000000],["スウ","Extreme","週",314380000],["カリーン","Normal","週",326370000],
["リンボ","Normal","週",487740000],["カロス","Chaos","週",580000000],["最初の対敵者","Hard","週",652300000],["暗黒の魔法使い","Hard","月",677250000],
["バルドリックス","Normal","週",700350000],["カリーン","Hard","週",862500000],["リンボ","Hard","週",984840000],["セレン","Extreme","週",1161600000],
["バルドリックス","Hard","週",1163340000],["最初の対敵者","Extreme","週",1457000000],["カロス","Extreme","週",1684800000],["カリーン","Extreme","週",2099440000],["暗黒の魔法使い","Extreme","月",4000000000]
];
const dropItems=[
{id:"loose",name:"ルージュコントロールマシンマーク",short:"ルーコン",cat:"漆黒",icon:"/assets/items/loose_control_machine_mark.jpeg"},
{id:"terror",name:"凄まじい恐怖",short:"恐怖",cat:"漆黒",icon:"/assets/items/endless_terror.jpeg"},
{id:"earring",name:"コマンダーフォースイヤリング",short:"コマフォ",cat:"漆黒",icon:"/assets/items/commanding_force_earring.jpeg"},
{id:"suffering",name:"苦痛の根源",short:"苦痛",cat:"漆黒",icon:"/assets/items/source_of_suffering.jpeg"},
{id:"mitra",name:"ミトラの怒り",short:"ミトラ",cat:"漆黒",icon:"/assets/items/mitras_rage.jpeg"},
{id:"belt",name:"夢幻のベルト",short:"夢幻",cat:"漆黒",icon:"/assets/items/dreamy_belt.jpeg"},
{id:"spellbook",name:"呪われた魔導書",short:"魔導書",cat:"漆黒",icon:"/assets/items/cursed_spellbook.png"},
{id:"eyepatch",name:"魔力が宿った眼帯",short:"眼帯",cat:"漆黒",icon:"/assets/items/magic_eyepatch.svg"},
{id:"heart",name:"黒い心臓",short:"黒心",cat:"漆黒",icon:"/assets/items/black_heart.svg"},
{id:"genesis_badge",name:"創世のバッジ",short:"創世バッジ",cat:"創世",icon:"/assets/items/genesis_badge.jpeg"},
{id:"eternal_hat",name:"エテルネル帽子",short:"帽子",cat:"エテルネル",icon:"/assets/items/eternal_hat.svg"},
{id:"eternal_top",name:"エテルネル上下",short:"上下",cat:"エテルネル",icon:"/assets/items/eternal_top.svg"},
{id:"eternal_gloves",name:"エテルネル手袋",short:"手袋",cat:"エテルネル",icon:"/assets/items/eternal_gloves.svg"},
{id:"eternal_shoes",name:"エテルネル靴",short:"靴",cat:"エテルネル",icon:"/assets/items/eternal_shoes.svg"},
{id:"eternal_cape",name:"エテルネルマント",short:"マント",cat:"エテルネル",icon:"/assets/items/eternal_cape.svg"},
{id:"other",name:"その他",short:"その他",cat:"その他",icon:""}];
const vipRanks=[{value:"none",label:"なし",resets:0},{value:"bronze",label:"ブロンズ（週1）",resets:1},{value:"silver",label:"シルバー（週2）",resets:2},{value:"royal",label:"ロイヤル（週3）",resets:3},{value:"custom",label:"カスタム",resets:-1}];
const defaultTasks=[["daily","モンスターパーク"],["daily","デイリーシンボル"],["daily","イベントデイリー"],["daily","ユニオンデイリー"],["weekly","週ボス"],["weekly","ウィークリーシンボル"],["weekly","ギルド関連"],["event","イベント交換"],["event","コイン確認"]] as const;

function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function makeBosses():Boss[]{return bossSeed.map((b,i)=>({id:uid(),order:i+1,name:b[0],difficulty:b[1],cycle:b[2],price:b[3]}))}
function makeCharacters():Character[]{return["リン","ユエ","キャラ3","キャラ4","キャラ5","キャラ6"].map((name,i)=>({id:uid(),name,memo:"",world:"くるみ",job:i===0?"リン":i===1?"隠月":"",level:"",order:i+1}))}
function makeRuns(chars:Character[],bosses:Boss[]):Run[]{return chars.flatMap(c=>bosses.map(b=>({id:uid(),characterId:c.id,bossId:b.id,cleared:false,vipReset:false,partySize:1,memo:""})))}
function makeTasks(chars:Character[]):Task[]{return chars.flatMap(c=>defaultTasks.map(t=>({id:uid(),characterId:c.id,type:t[0] as Task["type"],title:t[1],done:false})))}
function defaultState():AppState{const characters=makeCharacters();const bosses=makeBosses();return{characters,bosses,runs:makeRuns(characters,bosses),tasks:makeTasks(characters),drops:[],fragments:characters.flatMap(c=>["エテルネル帽子","エテルネルマント","創世のバッジ"].map((name,i)=>({id:uid(),characterId:c.id,name,part:name,current:0,required:i===2?1:24,weekly:0}))),growths:[],settlements:[],selectedCharacterId:characters[0].id,vipRank:"royal",customVipSlots:3,compact:false}}
function key(b:Boss){return`${b.name}|${b.difficulty}`}
function yen(v:number){return`${Math.round(v||0).toLocaleString()} メル`}
function shortDiff(d?:string){return d==="Extreme"?"EX":d==="Chaos"?"C":d==="Hard"?"H":d==="Normal"?"N":d==="Easy"?"E":d||""}
function bossText(b?:Boss){return b?`${shortDiff(b.difficulty)} ${b.name}`:"未選択"}
function format(ts:number){const d=new Date(ts);return`${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`}

function migrate(raw:Partial<AppState>):AppState{const fresh=defaultState();const characters=(raw.characters?.length?raw.characters:fresh.characters).map((c,i)=>({...c,order:i+1}));const oldBosses=raw.bosses||[];const oldByKey=new Map(oldBosses.map(b=>[key(b),b]));const bosses=bossSeed.map((s,i)=>{const old=oldByKey.get(`${s[0]}|${s[1]}`);return{id:old?.id||uid(),order:i+1,name:s[0],difficulty:s[1],cycle:s[2],price:s[3]}});const oldIdKey=new Map(oldBosses.map(b=>[b.id,key(b)]));const newId=new Map(bosses.map(b=>[key(b),b.id]));const valid=new Set(bosses.map(b=>b.id));const runs=(raw.runs||[]).map(r=>({...r,bossId:newId.get(oldIdKey.get(r.bossId)||"")||r.bossId,vipReset:Boolean(r.vipReset),partySize:Math.max(1,Number(r.partySize||1))})).filter(r=>valid.has(r.bossId));const runKeys=new Set(runs.map(r=>`${r.characterId}|${r.bossId}`));characters.forEach(c=>bosses.forEach(b=>{const k=`${c.id}|${b.id}`;if(!runKeys.has(k)){runs.push({id:uid(),characterId:c.id,bossId:b.id,cleared:false,vipReset:false,partySize:1,memo:""});runKeys.add(k)}}));const tasks=(raw.tasks||[]).filter(t=>characters.some(c=>c.id===t.characterId));const taskKeys=new Set(tasks.map(t=>`${t.characterId}|${t.type}|${t.title}`));characters.forEach(c=>defaultTasks.forEach(t=>{const k=`${c.id}|${t[0]}|${t[1]}`;if(!taskKeys.has(k)){tasks.push({id:uid(),characterId:c.id,type:t[0] as Task["type"],title:t[1],done:false});taskKeys.add(k)}}));return{characters,bosses,runs,tasks,drops:raw.drops||[],fragments:raw.fragments||fresh.fragments,growths:raw.growths||[],settlements:raw.settlements||[],selectedCharacterId:characters.some(c=>c.id===raw.selectedCharacterId)?raw.selectedCharacterId!:characters[0].id,vipRank:raw.vipRank||"royal",customVipSlots:Number(raw.customVipSlots??3),compact:Boolean(raw.compact)}}

function App(){const[state,setState]=useState<AppState>(()=>{try{const s=localStorage.getItem(LOCAL_KEY);return s?migrate(JSON.parse(s)):defaultState()}catch{return defaultState()}});const[user,setUser]=useState<User|null>(null);const[loaded,setLoaded]=useState(false);const[saving,setSaving]=useState(false);const[tab,setTab]=useState<"dash"|"boss"|"tasks"|"drops"|"frags"|"growth"|"stats"|"settings">("dash");const[search,setSearch]=useState("");const[dropItem,setDropItem]=useState("loose");const[dropBoss,setDropBoss]=useState("");const[dropMemo,setDropMemo]=useState("");
const bossMap=useMemo(()=>new Map(state.bosses.map(b=>[b.id,b])),[state.bosses]);const itemMap=useMemo(()=>new Map(dropItems.map(i=>[i.id,i])),[]);const selected=state.characters.find(c=>c.id===state.selectedCharacterId)||state.characters[0];const vipLimit=state.vipRank==="custom"?Math.max(0,Number(state.customVipSlots||0)):(vipRanks.find(v=>v.value===state.vipRank)?.resets||0);const sellLimit=BASE_SELL_LIMIT+vipLimit;
useEffect(()=>{if(!auth)return;return onAuthStateChanged(auth,async u=>{setUser(u);if(u&&db){const ref=doc(db,"users",u.uid,"app","trace-final");const snap=await getDoc(ref);if(snap.exists())setState(migrate(snap.data() as AppState));else await setDoc(ref,state);setLoaded(true)}else setLoaded(false)})},[]);
useEffect(()=>{localStorage.setItem(LOCAL_KEY,JSON.stringify(state))},[state]);async function saveCloud(next=state){if(!user||!db)return;setSaving(true);await setDoc(doc(db,"users",user.uid,"app","trace-final"),next);setSaving(false)}function update(fn:(s:AppState)=>AppState){setState(prev=>{const next=fn(prev);if(user)saveCloud(next);return next})}
const runs=useMemo(()=>state.runs.map(r=>{const boss=bossMap.get(r.bossId);return{...r,boss,share:(boss?.price||0)/Math.max(1,r.partySize||1)}}),[state.runs,bossMap]);const summaries=state.characters.map(c=>{const rs=runs.filter(r=>r.characterId===c.id&&r.cleared);const ts=state.tasks.filter(t=>t.characterId===c.id);const ds=state.drops.filter(d=>d.characterId===c.id);return{character:c,count:rs.length,vip:rs.filter(r=>r.vipReset).length,income:rs.reduce((s,r)=>s+r.share,0),tasksDone:ts.filter(t=>t.done).length,tasksTotal:ts.length,drops:ds.length}});const totalIncome=summaries.reduce((s,r)=>s+r.income,0),totalCount=summaries.reduce((s,r)=>s+r.count,0),totalVip=summaries.reduce((s,r)=>s+r.vip,0),totalDrops=state.drops.reduce((s,d)=>s+d.quantity,0);const selectedRuns=runs.filter(r=>r.characterId===selected.id);const currentRuns=selectedRuns.filter(r=>bossText(r.boss).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(a.boss?.order||0)-(b.boss?.order||0));const selectedCount=selectedRuns.filter(r=>r.cleared).length;const selectedVip=selectedRuns.filter(r=>r.cleared&&r.vipReset).length;const ranked=[...summaries].sort((a,b)=>b.income-a.income);const maxIncome=Math.max(1,...ranked.map(r=>r.income));
function eligibleVip(b?:Boss){if(!b||b.difficulty==="Extreme")return false;return["シグナス","ヒルラ","ピンクビーン","ジャクム","ピエール","バンバン","ブラッディクイーン","マグナス","ベルルム","ノウ姫","ビシャス","アケチミツヒデ","スウ","デミアン","ガーディアンエンジェルスライム","ルシード","ウィル","ダスク","デュンケル","真ヒルラ","暗黒の魔法使い","セレン","カロス","カリーン"].includes(b.name)}function sameBoss(run:Run,bossId=run.bossId){const b=bossMap.get(bossId);return state.runs.some(r=>r.id!==run.id&&r.characterId===run.characterId&&r.cleared&&bossMap.get(r.bossId)?.name===b?.name)}
function setRun(id:string,patch:Partial<Run>){const target=state.runs.find(r=>r.id===id);if(!target)return;const boss=bossMap.get(patch.bossId||target.bossId);const nextCleared=patch.cleared??target.cleared;const nextVip=patch.vipReset??target.vipReset;if(patch.cleared===true&&!target.cleared){if(selectedCount>=sellLimit){alert(`最大${sellLimit}体までです`);return}if(sameBoss(target,patch.bossId||target.bossId)){alert(`${boss?.name}は別難易度を選択済みです`);return}}if(nextVip){if(!nextCleared){alert("先にボスを選択してください");return}if(!eligibleVip(boss)){alert("VIP対象外です。EXは対象外です。");return}if(state.runs.filter(r=>r.characterId===target.characterId&&r.cleared&&r.vipReset&&r.id!==id).length>=vipLimit){alert(`VIP枠は${vipLimit}回までです`);return}}update(s=>({...s,runs:s.runs.map(r=>r.id===id?{...r,...patch,vipReset:nextCleared?nextVip:false}:r)}))}
function highSelect(){const ids=new Set<string>(),used=new Set<string>();selectedRuns.sort((a,b)=>(b.boss?.price||0)-(a.boss?.price||0)).forEach(r=>{const n=r.boss?.name||"";if(ids.size<sellLimit&&!used.has(n)){ids.add(r.id);used.add(n)}});update(s=>({...s,runs:s.runs.map(r=>r.characterId===selected.id?{...r,cleared:ids.has(r.id),vipReset:false}:r)}))}function clearChar(){update(s=>({...s,runs:s.runs.map(r=>r.characterId===selected.id?{...r,cleared:false,vipReset:false}:r)}))}function resetAll(){if(confirm("全チェックをリセットしますか？"))update(s=>({...s,runs:s.runs.map(r=>({...r,cleared:false,vipReset:false})),tasks:s.tasks.map(t=>({...t,done:false}))}))}function settle(){if(!totalCount)return alert("精算対象がありません");update(s=>({...s,settlements:[{id:uid(),createdAt:Date.now(),totalIncome,totalCrystals:totalCount,names:summaries.filter(x=>x.count).map(x=>x.character.name)},...s.settlements].slice(0,80)}))}
function addChar(){update(s=>{const c={id:uid(),name:`キャラ${s.characters.length+1}`,memo:"",world:"",job:"",level:"",order:s.characters.length+1};return{...s,characters:[...s.characters,c],runs:[...s.runs,...s.bosses.map(b=>({id:uid(),characterId:c.id,bossId:b.id,cleared:false,vipReset:false,partySize:1,memo:""}))],tasks:[...s.tasks,...defaultTasks.map(t=>({id:uid(),characterId:c.id,type:t[0] as Task["type"],title:t[1],done:false}))],selectedCharacterId:c.id}})}function addTask(type:Task["type"]){const title=prompt("タスク名");if(title)update(s=>({...s,tasks:[...s.tasks,{id:uid(),characterId:selected.id,title,type,done:false}]}))}function addDrop(){const item=itemMap.get(dropItem)||dropItems[0];const bossId=dropBoss||state.bosses[0]?.id;if(!bossId)return;update(s=>({...s,drops:[{id:uid(),characterId:selected.id,bossId,itemId:item.id,itemName:item.name,category:item.cat,quantity:1,obtainedAt:Date.now(),memo:dropMemo},...s.drops]}));setDropMemo("")}function addGrowth(){update(s=>({...s,growths:[{id:uid(),characterId:selected.id,date:Date.now(),score:"",mainStat:"",patch:"",memo:""},...s.growths]}))}
return <div className={`app ${state.compact?"compact":""}`}><aside className="side"><div className="brand"><div>◇</div><strong>Maple<br/>Manager</strong></div>{[["dash",Home,"ダッシュボード"],["boss",Coins,"ボス結晶"],["tasks",ClipboardCheck,"日課/週課"],["drops",Package,"ドロップ"],["frags",Database,"欠片シミュ"],["growth",Trophy,"成長記録"],["stats",BarChart3,"統計"],["settings",Settings,"設定"]].map(([k,I,l]:any)=><button key={k} onClick={()=>setTab(k)} className={tab===k?"active":""}><I size={18}/><span>{l}</span><ChevronRight size={14}/></button>)}</aside><main className="main"><header className="top"><div><h1>{tab==="dash"?"ダッシュボード":tab==="boss"?"ボス結晶管理":tab==="tasks"?"日課・週課管理":tab==="drops"?"ドロップ管理":tab==="frags"?"欠片シミュ":tab==="growth"?"成長記録":tab==="stats"?"統計レポート":"設定"}</h1><p>Firebase同期対応 / PC・iPhone連携</p></div><div className="topRight"><select value={state.vipRank} onChange={e=>update(s=>({...s,vipRank:e.target.value}))}>{vipRanks.map(v=><option key={v.value} value={v.value}>VIP：{v.label}</option>)}</select>{state.vipRank==="custom"&&<input className="miniInput" type="number" value={state.customVipSlots} onChange={e=>update(s=>({...s,customVipSlots:Number(e.target.value||0)}))}/>}<span className="pill">VIP {totalVip}/{vipLimit}</span>{firebaseReady?user?<><button onClick={()=>saveCloud()}><Save size={15}/>{saving?"保存中":"保存"}</button><button onClick={logout}><LogOut size={15}/>ログアウト</button></>:<button className="primary" onClick={loginWithGoogle}><LogIn size={15}/>Googleで同期</button>:<span className="pill warn">Firebase未設定</span>}</div></header><section className="kpis"><div className="kpi navy"><span>今週の予想収益</span><b>{yen(totalIncome)}</b><em>チェック済み {totalCount} 個</em></div><div className="kpi gold"><span>今週の確定収益</span><b>{yen(totalIncome)}</b><em>VIP {totalVip}/{vipLimit}</em></div><div className="kpi white"><button className="settle" onClick={settle}>精算を実行する</button><button onClick={resetAll}><RotateCcw size={15}/>週リセット</button><small>同期状態：{user?(loaded?"ON":"読込中"):"OFF"}</small></div></section>
{tab==="dash"&&<section className="dashGrid"><div className="panel wide"><h2>キャラクター状況</h2><div className="charCards">{summaries.map(s=><button key={s.character.id} className={selected.id===s.character.id?"char selected":"char"} onClick={()=>{update(st=>({...st,selectedCharacterId:s.character.id}));setTab("boss")}}><i>{s.character.name.slice(0,2)}</i><div><b>{s.character.name}</b><span>{s.character.memo||"未設定"}</span></div><strong>{yen(s.income)}</strong><footer><em>ボス {s.count}/{sellLimit}</em><em>日課 {s.tasksDone}/{s.tasksTotal}</em><em>Drop {s.drops}</em></footer></button>)}</div></div><div className="panel"><h2>最近のドロップ</h2>{state.drops.slice(0,6).map(d=>{const item=itemMap.get(d.itemId);return <div className="miniDrop" key={d.id}><img src={item?.icon}/><span>{d.itemName}</span></div>})}{!state.drops.length&&<p className="muted">まだ記録がありません。</p>}</div></section>}
{tab==="boss"&&<section className="work"><aside className="charList">{state.characters.map(c=>{const s=summaries.find(x=>x.character.id===c)!;return <button key={c.id} onClick={()=>update(st=>({...st,selectedCharacterId:c.id}))} className={selected.id===c.id?"on":""}><i>{c.name.slice(0,2)}</i><b>{c.name}</b><span>{s.count}体 / VIP {s.vip}</span></button>})}</aside><div className="panel grow"><div className="toolbar"><div><h2>{selected.name}</h2><p>同じボスは1難易度だけ。EXはVIP対象外。</p></div><input placeholder="検索" value={search} onChange={e=>setSearch(e.target.value)}/><span className="pill">{selectedCount}/{sellLimit}</span><span className="pill orange">VIP {selectedVip}/{vipLimit}</span><button onClick={highSelect}>全選択</button><button onClick={clearChar}>全解除</button></div><div className="bossGrid">{currentRuns.map(r=>{const disabled=!r.cleared&&selectedCount>=sellLimit||sameBoss(r as Run);return <div key={r.id} className={`boss ${r.cleared?"checked":""} ${r.vipReset?"vip":""} ${disabled?"disabled":""}`} onClick={()=>!disabled&&setRun(r.id,{cleared:!r.cleared,vipReset:r.cleared?false:r.vipReset})}><div className="bossTop"><i>{r.cleared?"✓":""}</i><b>{bossText(r.boss)}</b>{eligibleVip(r.boss)&&<button onClick={e=>{e.stopPropagation();setRun(r.id,{vipReset:!r.vipReset})}}>♕ VIP</button>}</div><strong>{yen(r.share)}</strong><label onClick={e=>e.stopPropagation()}>人数<select value={r.partySize} onChange={e=>setRun(r.id,{partySize:Number(e.target.value)})}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n}人</option>)}</select></label></div>})}</div></div></section>}
{tab==="tasks"&&<section className="tasks">{(["daily","weekly","event"] as const).map(type=><div className="panel" key={type}><h2>{type==="daily"?"日課":type==="weekly"?"週課":"イベント"}<button onClick={()=>addTask(type)}><Plus size={14}/>追加</button></h2>{state.tasks.filter(t=>t.characterId===selected.id&&t.type===type).map(t=><label className={t.done?"task done":"task"} key={t.id}><input type="checkbox" checked={t.done} onChange={e=>update(s=>({...s,tasks:s.tasks.map(x=>x.id===t.id?{...x,done:e.target.checked}:x)}))}/><span>{t.title}</span><button onClick={()=>update(s=>({...s,tasks:s.tasks.filter(x=>x.id!==t.id)}))}>削除</button></label>)}</div>)}</section>}
{tab==="drops"&&<section className="drops"><div className="panel dropForm"><h2>ドロップ記録</h2><select value={dropItem} onChange={e=>setDropItem(e.target.value)}>{dropItems.map(i=><option key={i.id} value={i.id}>{i.cat}：{i.name}</option>)}</select><select value={dropBoss||state.bosses[0]?.id} onChange={e=>setDropBoss(e.target.value)}>{state.bosses.map(b=><option key={b.id} value={b.id}>{bossText(b)}</option>)}</select><input placeholder="メモ" value={dropMemo} onChange={e=>setDropMemo(e.target.value)}/><button className="primary" onClick={addDrop}>追加</button></div><div className="panel wide"><h2>アイテム一覧</h2><div className="itemGrid">{dropItems.map(i=><button key={i.id} onClick={()=>setDropItem(i.id)} className={dropItem===i.id?"item active":"item"}>{i.icon?<img src={i.icon}/>:<span/>}<b>{i.short}</b><em>{i.cat}</em></button>)}</div></div><div className="panel full"><h2>ドロップ履歴</h2>{state.drops.map(d=>{const i=itemMap.get(d.itemId);return <div className="dropRow" key={d.id}><img src={i?.icon}/><div><b>{d.itemName}</b><span>{state.characters.find(c=>c.id===d.characterId)?.name} / {bossText(bossMap.get(d.bossId))} / {format(d.obtainedAt)} {d.memo&&`/ ${d.memo}`}</span></div><button onClick={()=>update(s=>({...s,drops:s.drops.filter(x=>x.id!==d.id)}))}>削除</button></div>})}{!state.drops.length&&<p className="muted">まだ記録がありません。</p>}</div></section>}
{tab==="frags"&&<section className="frags"><div className="panel full"><h2>欠片シミュ</h2>{state.fragments.filter(f=>f.characterId===selected.id).map(f=>{const remain=Math.max(0,f.required-f.current);const weeks=f.weekly>0?Math.ceil(remain/f.weekly):0;return <div className="frag" key={f.id}><b>{f.name}</b><span>{f.current}/{f.required}</span><progress value={f.current} max={f.required}/><input type="number" value={f.current} onChange={e=>update(s=>({...s,fragments:s.fragments.map(x=>x.id===f.id?{...x,current:Number(e.target.value||0)}:x)}))}/><input type="number" value={f.required} onChange={e=>update(s=>({...s,fragments:s.fragments.map(x=>x.id===f.id?{...x,required:Number(e.target.value||0)}:x)}))}/><input type="number" value={f.weekly} onChange={e=>update(s=>({...s,fragments:s.fragments.map(x=>x.id===f.id?{...x,weekly:Number(e.target.value||0)}:x)}))}/><em>{f.weekly>0?`約${weeks}週`:"週入手を入力"}</em></div>})}</div></section>}
{tab==="growth"&&<section className="growth"><div className="panel full"><h2>成長記録 <button onClick={addGrowth}>追加</button></h2>{state.growths.filter(g=>g.characterId===selected.id).map(g=><div className="growthRow" key={g.id}><input placeholder="水晶/戦闘力" value={g.score} onChange={e=>update(s=>({...s,growths:s.growths.map(x=>x.id===g.id?{...x,score:e.target.value}:x)}))}/><input placeholder="メインステ" value={g.mainStat} onChange={e=>update(s=>({...s,growths:s.growths.map(x=>x.id===g.id?{...x,mainStat:e.target.value}:x)}))}/><input placeholder="パッチ/イベント" value={g.patch} onChange={e=>update(s=>({...s,growths:s.growths.map(x=>x.id===g.id?{...x,patch:e.target.value}:x)}))}/><input placeholder="メモ" value={g.memo} onChange={e=>update(s=>({...s,growths:s.growths.map(x=>x.id===g.id?{...x,memo:e.target.value}:x)}))}/><button onClick={()=>update(s=>({...s,growths:s.growths.filter(x=>x.id!==g.id)}))}>削除</button></div>)}</div></section>}
{tab==="stats"&&<section className="report"><div className="reportHero"><div><h2>統計レポート</h2><p>クイック表示： <button>全表示</button><button>今週</button><button>今月</button></p></div><div className="total"><span>選択中の合計収益</span><b>{yen(totalIncome)}</b><em>{totalCount}個 / VIP {totalVip} / Drop {totalDrops}</em></div></div><h2>キャラクター別収支</h2><div className="rank">{ranked.map((s,i)=><div key={s.character.id}><strong>{i+1}</strong><i>{s.character.name.slice(0,2)}</i><p><b>{s.character.name}</b><u><span style={{width:`${Math.max(3,s.income/maxIncome*100)}%`}}/></u></p><em>{yen(s.income)}</em></div>)}</div><h2>期間内の精算履歴</h2><div className="history">{state.settlements.length?state.settlements.map(h=><div key={h.id}><FileText size={18}/><span>{format(h.createdAt)} / {h.names.join("、")}</span><b>{yen(h.totalIncome)}</b><button onClick={()=>update(s=>({...s,settlements:s.settlements.filter(x=>x.id!==h.id)}))}>削除</button></div>):<p className="muted">まだ精算履歴がありません。</p>}</div></section>}
{tab==="settings"&&<section className="settingsPage"><div className="panel full"><h2>キャラ設定 <button onClick={addChar}><Plus size={14}/>追加</button></h2>{state.characters.map(c=><div className="edit" key={c.id}><input value={c.name} onChange={e=>update(s=>({...s,characters:s.characters.map(x=>x.id===c.id?{...x,name:e.target.value}:x)}))}/><input placeholder="職業" value={c.job||""} onChange={e=>update(s=>({...s,characters:s.characters.map(x=>x.id===c.id?{...x,job:e.target.value}:x)}))}/><input placeholder="メモ" value={c.memo} onChange={e=>update(s=>({...s,characters:s.characters.map(x=>x.id===c.id?{...x,memo:e.target.value}:x)}))}/><button onClick={()=>update(s=>({...s,characters:s.characters.filter(x=>x.id!==c.id),runs:s.runs.filter(r=>r.characterId!==c.id)}))}><Trash2 size={14}/>削除</button></div>)}<label className="switch"><input type="checkbox" checked={state.compact} onChange={e=>update(s=>({...s,compact:e.target.checked}))}/> Compact表示</label></div><div className="panel full"><h2>ボス価格マスタ</h2>{state.bosses.map(b=><div className="price" key={b.id}><input type="number" value={b.order}/><input value={b.name} onChange={e=>update(s=>({...s,bosses:s.bosses.map(x=>x.id===b.id?{...x,name:e.target.value}:x)}))}/><input value={b.difficulty} onChange={e=>update(s=>({...s,bosses:s.bosses.map(x=>x.id===b.id?{...x,difficulty:e.target.value}:x)}))}/><input type="number" value={b.price} onChange={e=>update(s=>({...s,bosses:s.bosses.map(x=>x.id===b.id?{...x,price:Number(e.target.value||0)}:x)}))}/></div>)}</div></section>}
</main></div>}
createRoot(document.getElementById("root")!).render(<App/>);
